/* tslint:disable */
/* eslint-disable */
/**
 * Bites Anomaly Detection API
 * API for the Bites Anomaly Detection project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * GeoApi - axios parameter creator
 * @export
 */
export const GeoApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * ViewSet for the Municipality model with MVT rendering.
         * @param {number} x 
         * @param {number} y 
         * @param {number} z 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tilesRetrieve: async (x: number, y: number, z: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'x' is not null or undefined
            assertParamExists('tilesRetrieve', 'x', x)
            // verify required parameter 'y' is not null or undefined
            assertParamExists('tilesRetrieve', 'y', y)
            // verify required parameter 'z' is not null or undefined
            assertParamExists('tilesRetrieve', 'z', z)
            const localVarPath = `/geo/tiles/{z}/{x}/{y}`
                .replace(`{${"x"}}`, encodeURIComponent(String(x)))
                .replace(`{${"y"}}`, encodeURIComponent(String(y)))
                .replace(`{${"z"}}`, encodeURIComponent(String(z)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GeoApi - functional programming interface
 * @export
 */
export const GeoApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GeoApiAxiosParamCreator(configuration)
    return {
        /**
         * ViewSet for the Municipality model with MVT rendering.
         * @param {number} x 
         * @param {number} y 
         * @param {number} z 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tilesRetrieve(x: number, y: number, z: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tilesRetrieve(x, y, z, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GeoApi.tilesRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GeoApi - factory interface
 * @export
 */
export const GeoApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GeoApiFp(configuration)
    return {
        /**
         * ViewSet for the Municipality model with MVT rendering.
         * @param {GeoApiTilesRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tilesRetrieve(requestParameters: GeoApiTilesRetrieveRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.tilesRetrieve(requestParameters.x, requestParameters.y, requestParameters.z, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for tilesRetrieve operation in GeoApi.
 * @export
 * @interface GeoApiTilesRetrieveRequest
 */
export interface GeoApiTilesRetrieveRequest {
    /**
     * 
     * @type {number}
     * @memberof GeoApiTilesRetrieve
     */
    readonly x: number

    /**
     * 
     * @type {number}
     * @memberof GeoApiTilesRetrieve
     */
    readonly y: number

    /**
     * 
     * @type {number}
     * @memberof GeoApiTilesRetrieve
     */
    readonly z: number
}

/**
 * GeoApi - object-oriented interface
 * @export
 * @class GeoApi
 * @extends {BaseAPI}
 */
export class GeoApi extends BaseAPI {
    /**
     * ViewSet for the Municipality model with MVT rendering.
     * @param {GeoApiTilesRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GeoApi
     */
    public tilesRetrieve(requestParameters: GeoApiTilesRetrieveRequest, options?: RawAxiosRequestConfig) {
        return GeoApiFp(this.configuration).tilesRetrieve(requestParameters.x, requestParameters.y, requestParameters.z, options).then((request) => request(this.axios, this.basePath));
    }
}

