/* tslint:disable */
/* eslint-disable */
/**
 * Metrics API
 * API for the Metrics of the Mosquito Alert project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SchemaOpenapiJsonRetrieveLangParameter } from '../models';
// @ts-ignore
import type { SchemaOpenapiYmlRetrieveFormatParameter } from '../models';
/**
 * SchemaApi - axios parameter creator
 * @export
 */
export const SchemaApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
         * @param {SchemaOpenapiJsonRetrieveLangParameter} [lang] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openapiJsonRetrieve: async (lang?: SchemaOpenapiJsonRetrieveLangParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/schema/openapi.json`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (lang !== undefined) {
                localVarQueryParameter['lang'] = lang;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
         * @param {SchemaOpenapiYmlRetrieveFormatParameter} [format] 
         * @param {SchemaOpenapiJsonRetrieveLangParameter} [lang] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openapiYmlRetrieve: async (format?: SchemaOpenapiYmlRetrieveFormatParameter, lang?: SchemaOpenapiJsonRetrieveLangParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/schema/openapi.yml`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication tokenAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (format !== undefined) {
                localVarQueryParameter['format'] = format;
            }

            if (lang !== undefined) {
                localVarQueryParameter['lang'] = lang;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SchemaApi - functional programming interface
 * @export
 */
export const SchemaApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SchemaApiAxiosParamCreator(configuration)
    return {
        /**
         * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
         * @param {SchemaOpenapiJsonRetrieveLangParameter} [lang] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openapiJsonRetrieve(lang?: SchemaOpenapiJsonRetrieveLangParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openapiJsonRetrieve(lang, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchemaApi.openapiJsonRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
         * @param {SchemaOpenapiYmlRetrieveFormatParameter} [format] 
         * @param {SchemaOpenapiJsonRetrieveLangParameter} [lang] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async openapiYmlRetrieve(format?: SchemaOpenapiYmlRetrieveFormatParameter, lang?: SchemaOpenapiJsonRetrieveLangParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.openapiYmlRetrieve(format, lang, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SchemaApi.openapiYmlRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SchemaApi - factory interface
 * @export
 */
export const SchemaApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SchemaApiFp(configuration)
    return {
        /**
         * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
         * @param {SchemaApiOpenapiJsonRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openapiJsonRetrieve(requestParameters: SchemaApiOpenapiJsonRetrieveRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.openapiJsonRetrieve(requestParameters.lang, options).then((request) => request(axios, basePath));
        },
        /**
         * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
         * @param {SchemaApiOpenapiYmlRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        openapiYmlRetrieve(requestParameters: SchemaApiOpenapiYmlRetrieveRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.openapiYmlRetrieve(requestParameters.format, requestParameters.lang, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for openapiJsonRetrieve operation in SchemaApi.
 * @export
 * @interface SchemaApiOpenapiJsonRetrieveRequest
 */
export interface SchemaApiOpenapiJsonRetrieveRequest {
    /**
     * 
     * @type {SchemaOpenapiJsonRetrieveLangParameter}
     * @memberof SchemaApiOpenapiJsonRetrieve
     */
    readonly lang?: SchemaOpenapiJsonRetrieveLangParameter
}

/**
 * Request parameters for openapiYmlRetrieve operation in SchemaApi.
 * @export
 * @interface SchemaApiOpenapiYmlRetrieveRequest
 */
export interface SchemaApiOpenapiYmlRetrieveRequest {
    /**
     * 
     * @type {SchemaOpenapiYmlRetrieveFormatParameter}
     * @memberof SchemaApiOpenapiYmlRetrieve
     */
    readonly format?: SchemaOpenapiYmlRetrieveFormatParameter

    /**
     * 
     * @type {SchemaOpenapiJsonRetrieveLangParameter}
     * @memberof SchemaApiOpenapiYmlRetrieve
     */
    readonly lang?: SchemaOpenapiJsonRetrieveLangParameter
}

/**
 * SchemaApi - object-oriented interface
 * @export
 * @class SchemaApi
 * @extends {BaseAPI}
 */
export class SchemaApi extends BaseAPI {
    /**
     * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
     * @param {SchemaApiOpenapiJsonRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SchemaApi
     */
    public openapiJsonRetrieve(requestParameters: SchemaApiOpenapiJsonRetrieveRequest = {}, options?: RawAxiosRequestConfig) {
        return SchemaApiFp(this.configuration).openapiJsonRetrieve(requestParameters.lang, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * OpenApi3 schema for this API. Format can be selected via content negotiation.  - YAML: application/vnd.oai.openapi - JSON: application/vnd.oai.openapi+json
     * @param {SchemaApiOpenapiYmlRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SchemaApi
     */
    public openapiYmlRetrieve(requestParameters: SchemaApiOpenapiYmlRetrieveRequest = {}, options?: RawAxiosRequestConfig) {
        return SchemaApiFp(this.configuration).openapiYmlRetrieve(requestParameters.format, requestParameters.lang, options).then((request) => request(this.axios, this.basePath));
    }
}

