/* tslint:disable */
/* eslint-disable */
/**
 * Bites Anomaly Detection API
 * API for the Bites Anomaly Detection project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * TimeseriesJsonApi - axios parameter creator
 * @export
 */
export const TimeseriesJsonApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} date Date of the results to return.
         * @param {number} [days] Number of days to return in the time series.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jsonRetrieve: async (date: string, days?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'date' is not null or undefined
            assertParamExists('jsonRetrieve', 'date', date)
            const localVarPath = `/timeseries-json/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (date !== undefined) {
                localVarQueryParameter['date'] = (date as any instanceof Date) ?
                    (date as any).toISOString().substring(0,10) :
                    date;
            }

            if (days !== undefined) {
                localVarQueryParameter['days'] = days;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TimeseriesJsonApi - functional programming interface
 * @export
 */
export const TimeseriesJsonApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TimeseriesJsonApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} date Date of the results to return.
         * @param {number} [days] Number of days to return in the time series.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async jsonRetrieve(date: string, days?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.jsonRetrieve(date, days, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TimeseriesJsonApi.jsonRetrieve']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TimeseriesJsonApi - factory interface
 * @export
 */
export const TimeseriesJsonApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TimeseriesJsonApiFp(configuration)
    return {
        /**
         * 
         * @param {TimeseriesJsonApiJsonRetrieveRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        jsonRetrieve(requestParameters: TimeseriesJsonApiJsonRetrieveRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.jsonRetrieve(requestParameters.date, requestParameters.days, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for jsonRetrieve operation in TimeseriesJsonApi.
 * @export
 * @interface TimeseriesJsonApiJsonRetrieveRequest
 */
export interface TimeseriesJsonApiJsonRetrieveRequest {
    /**
     * Date of the results to return.
     * @type {string}
     * @memberof TimeseriesJsonApiJsonRetrieve
     */
    readonly date: string

    /**
     * Number of days to return in the time series.
     * @type {number}
     * @memberof TimeseriesJsonApiJsonRetrieve
     */
    readonly days?: number
}

/**
 * TimeseriesJsonApi - object-oriented interface
 * @export
 * @class TimeseriesJsonApi
 * @extends {BaseAPI}
 */
export class TimeseriesJsonApi extends BaseAPI {
    /**
     * 
     * @param {TimeseriesJsonApiJsonRetrieveRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TimeseriesJsonApi
     */
    public jsonRetrieve(requestParameters: TimeseriesJsonApiJsonRetrieveRequest, options?: RawAxiosRequestConfig) {
        return TimeseriesJsonApiFp(this.configuration).jsonRetrieve(requestParameters.date, requestParameters.days, options).then((request) => request(this.axios, this.basePath));
    }
}

