/* tslint:disable */
/* eslint-disable */
/**
 * Bites Anomaly Detection API
 * API for the Bites Anomaly Detection project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Serializer for the Metric Executions.
 * @export
 * @interface LastMetricDate
 */
export interface LastMetricDate {
    /**
     * 
     * @type {string}
     * @memberof LastMetricDate
     */
    'date': string;
}

