/* tslint:disable */
/* eslint-disable */
/**
 * Bites Anomaly Detection API
 * API for the Bites Anomaly Detection project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Serializer for the Metrics.
 * @export
 * @interface Metric
 */
export interface Metric {
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    'id': string;
    /**
     * The date of the metric.
     * @type {string}
     * @memberof Metric
     */
    'date': string;
    /**
     * The actual value of the metric.
     * @type {number}
     * @memberof Metric
     */
    'value'?: number | null;
    /**
     * The predicted value of the metric. This value will be estimated at creation.
     * @type {number}
     * @memberof Metric
     */
    'predicted_value'?: number | null;
    /**
     * The predicted lower band value of the metric, from which values will be             considerated as anomalies. This value will be estimated at creation.
     * @type {number}
     * @memberof Metric
     */
    'lower_value'?: number | null;
    /**
     * The predicted upper band value of the metric, from which values will be             considerated as anomalies. This value will be estimated at creation.
     * @type {number}
     * @memberof Metric
     */
    'upper_value'?: number | null;
    /**
     * The degree of the anomaly, a range of values that starts on -1 (a lower anomaly of the             highest degree) and ends on +1 (a upper anomaly of the highest degree). The 0 value means that             these is no anomaly. This value will be estimated at creation.
     * @type {number}
     * @memberof Metric
     */
    'anomaly_degree': number | null;
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    'region_code': string;
}

