/* tslint:disable */
/* eslint-disable */
/**
 * Bites Anomaly Detection API
 * API for the Bites Anomaly Detection project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Serializer for the Metric Seasonality associated to the Predictor model.
 * @export
 * @interface MetricSeasonality
 */
export interface MetricSeasonality {
    /**
     * The predicted seasonality for the metric.
     * @type {Array<number>}
     * @memberof MetricSeasonality
     */
    'yearly'?: Array<number> | null;
}

