/* tslint:disable */
/* eslint-disable */
/**
 * Metrics API
 * API for the Metrics of the Mosquito Alert project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MunicipalityRetrieveGeometry } from './municipality-retrieve-geometry';
// May contain unused imports in some cases
// @ts-ignore
import type { MunicipalityRetrieveProperties } from './municipality-retrieve-properties';
// May contain unused imports in some cases
// @ts-ignore
import type { MunicipalityRetrieveType } from './municipality-retrieve-type';

/**
 * Serializer for the Municipality model.
 * @export
 * @interface MunicipalityRetrieve
 */
export interface MunicipalityRetrieve {
    /**
     * 
     * @type {MunicipalityRetrieveType}
     * @memberof MunicipalityRetrieve
     */
    'type'?: MunicipalityRetrieveType;
    /**
     * 
     * @type {number}
     * @memberof MunicipalityRetrieve
     */
    'id'?: number;
    /**
     * 
     * @type {MunicipalityRetrieveGeometry}
     * @memberof MunicipalityRetrieve
     */
    'geometry'?: MunicipalityRetrieveGeometry;
    /**
     * 
     * @type {MunicipalityRetrieveProperties}
     * @memberof MunicipalityRetrieve
     */
    'properties'?: MunicipalityRetrieveProperties;
}



