/* tslint:disable */
/* eslint-disable */
/**
 * Metrics API
 * API for the Metrics of the Mosquito Alert project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MunicipalityRetrieveProperties
 */
export interface MunicipalityRetrieveProperties {
    /**
     * The unique code that identifies the region.
     * @type {string}
     * @memberof MunicipalityRetrieveProperties
     */
    'code'?: string;
    /**
     * The name of the region.
     * @type {string}
     * @memberof MunicipalityRetrieveProperties
     */
    'name'?: string;
    /**
     * Alternative names for the region. If there is more than one, they will be delimited by \"|\".
     * @type {string}
     * @memberof MunicipalityRetrieveProperties
     */
    'alt_name'?: string | null;
    /**
     * Get the province name from the province related model.
     * @type {string}
     * @memberof MunicipalityRetrieveProperties
     */
    'province'?: string;
}

