/* tslint:disable */
/* eslint-disable */
/**
 * Metrics API
 * API for the Metrics of the Mosquito Alert project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MunicipalityRetrieveGeometryType } from './municipality-retrieve-geometry-type';

/**
 * 
 * @export
 * @interface MunicipalityRetrieveGeometry
 */
export interface MunicipalityRetrieveGeometry {
    /**
     * 
     * @type {MunicipalityRetrieveGeometryType}
     * @memberof MunicipalityRetrieveGeometry
     */
    'type'?: MunicipalityRetrieveGeometryType;
    /**
     * 
     * @type {Array<Array<Array<Array<number>>>>}
     * @memberof MunicipalityRetrieveGeometry
     */
    'coordinates'?: Array<Array<Array<Array<number>>>>;
}



