/* tslint:disable */
/* eslint-disable */
/**
 * Metrics API
 * API for the Metrics of the Mosquito Alert project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const MunicipalityRetrieveType = {
    Feature: 'Feature',
    UnknownDefaultOpenApi: '11184809'
} as const;

export type MunicipalityRetrieveType = typeof MunicipalityRetrieveType[keyof typeof MunicipalityRetrieveType];



