/* tslint:disable */
/* eslint-disable */
/**
 * Bites Anomaly Detection API
 * API for the Bites Anomaly Detection project
 *
 * The version of the OpenAPI document: 1.0.0 (v1)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Municipality } from './municipality';

/**
 * 
 * @export
 * @interface PaginatedMunicipalityList
 */
export interface PaginatedMunicipalityList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedMunicipalityList
     */
    'count': number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMunicipalityList
     */
    'next'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMunicipalityList
     */
    'previous'?: string | null;
    /**
     * 
     * @type {Array<Municipality>}
     * @memberof PaginatedMunicipalityList
     */
    'results': Array<Municipality>;
}

